---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 11-jdk

inputs:
- name: src
- name: src-ci

params:
  BUILD_PATH:
  ENVIRONMENT_FILE:

run:
  path: src-ci/ci/tasks/maven/maven-test.sh